CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1,
    created REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY, csrf TEXT NOT NULL, user_id TEXT,
    stage TEXT NOT NULL, expires REAL NOT NULL,
    code_hash TEXT, code_expires REAL, attempts INTEGER NOT NULL DEFAULT 0,
    sent REAL NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS limits (key TEXT NOT NULL, at REAL NOT NULL);
CREATE INDEX IF NOT EXISTS limits_key ON limits(key, at);
CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY, name TEXT NOT NULL, title TEXT NOT NULL,
    sha256 TEXT NOT NULL, chunks INTEGER NOT NULL, size INTEGER NOT NULL,
    created REAL NOT NULL, deleted INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY, action TEXT NOT NULL, status TEXT NOT NULL,
    message TEXT NOT NULL, created REAL NOT NULL, finished REAL,
    revision TEXT, actor TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS audit (
    id INTEGER PRIMARY KEY AUTOINCREMENT, at REAL NOT NULL,
    actor TEXT NOT NULL, action TEXT NOT NULL, detail TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS revisions (id TEXT PRIMARY KEY, created REAL NOT NULL);
